### ISSUE TITLE
Missing entities

### ISSUE THREAD

**Issue by querys1** [SukramJ/hahomematic#730] opened 2022-12-04 16:36 UTC
DONT'T DELETE THIS.

Please answer all questions as good as possible.

Language: english

Make sure you have read the documentation at https://github.com/danielperna84/custom_homematic#custom_homematic.

Make sure you have read the release notes at https://github.com/danielperna84/custom_homematic/releases. 

Make sure you are running the latest version of the custom_component (and Home Assistant) before reporting an issue.

ENSURE that your Backend (CCU/Homegear/...) is working as expected and connected devices are controllable.

**custom_component version (if applicable):**
1.22.0

**known last working custom_component version (if applicable):**
1.21.3

**Home Assistant version (if applicable):**
2022.11.5

**CCU version:**
- Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, HA-Addon ...) Raspberrymatic in KVM QEMU
- OS (Original, RaspberryMatic, debmatic ...): Rasberrymatic 
- Version: raspmatic_ova (3.65.11.20221005)

**Problem-relevant configuration:**

Do you use tls? no
Do you use callback? no
Do you use username and password? yes
Which interfaces do you use (hmip/bidcos/wired)? hmip

**Describe the bug**
Some entities are missing. 
The Homematic IP FAL230 provides binary entities for activated/deactived heating circles. They are not longer available in this version.

As far as I remember all "binary" sensors are missing. The Low Battery for the hmip-WTH-2 was also unavailable.

**To Reproduce**
they are not deactivated, they are missing.

**Screenshots (if applicable)**
![example](https://user-images.githubusercontent.com/116440848/205503112-6ce3df04-1cef-4976-8699-e6625ef4a6d1.jpg)
Example for the FAL230 Heating Circuits (shows only on or off).

**Relevant HA log entries (full log)**
working previous version:
[config_entry-homematicip_local-924e2004b1f743a5d096170c62628b99.json.txt](https://github.com/danielperna84/hahomematic/files/10149009/config_entry-homematicip_local-924e2004b1f743a5d096170c62628b99.json.txt)

not working new version

[config_entry-homematicip_local-5db11752605636bc471f3f3b64f4d3b5.json.txt](https://github.com/danielperna84/hahomematic/files/10149010/config_entry-homematicip_local-5db11752605636bc471f3f3b64f4d3b5.json.txt)

```

**Diagnostic Information (available on every device)**
```

```

**Expected behavior**
A clear and concise description of what you expected to happen.

**Additional context**
Add any other context about the problem here.

**Comment by SukramJ** [comment] 2022-12-04 16:39
Sorry, i cannot reproduce this on my systems, and you did not add any further information like logs.
These diagnostic data are statistics only.

Repeat the update and see if the problem is there again, and add logs!

**Comment by querys1** [comment] 2022-12-04 16:40
what logs do you want and how do I save and get them?

**Comment by SukramJ** [comment] 2022-12-04 16:42
Home Assistant logs. 
But this is only relevant if you update again to the latest version.

I need to know which entities by name (entity_id) and not by count are missing in the latest version on your systems.

**Comment by querys1** [comment] 2022-12-04 16:45
For example the
binary_sensor.hmip_fal230_c6_erdgeschoss_state_ch1
binary_sensor.hmip_fal230_c6_erdgeschoss_state_ch2
binary_sensor.hmip_fal230_c6_erdgeschoss_state_ch3
binary_sensor.hmip_fal230_c6_erdgeschoss_state_ch4
binary_sensor.hmip_fal230_c6_erdgeschoss_state_ch5
binary_sensor.hmip_fal230_c6_erdgeschoss_state_ch6

was missing and for example the 
binary_sensor.arbeitszimmer_low_battery

was missing too.

I will upgrade to the new version as soon as possible, currently I'm running out of time.

**Comment by SukramJ** [comment] 2022-12-04 16:53
As already mention i cannot reproduce this as my Fal230 C6 has these state entities also with the latest version.

**Comment by SukramJ** [comment] 2022-12-04 16:54
I close this  for now. 
Please come back after upgrading to the latest version and add relevant log entries from HA Log (full log)

**Closed as completed by SukramJ** 2022-12-04 16:54 UTC
