### ISSUE TITLE
add same sensors for heating groups

### ISSUE THREAD

**Issue by Bascht74** [SukramJ/hahomematic#654] opened 2022-10-16 09:34 UTC
**custom_component version (if applicable):**
1.19.5

**known last working custom_component version (if applicable):**
./.

**Home Assistant version (if applicable):**
2022.10.4

**CCU version:**
- Model: HA-Addon
- OS: RaspberryMatic
- Version: 3.65.11.20221005

**Problem-relevant configuration:**

Do you use tls? no
Do you use callback? don't know, but not relevant I think
Do you use username and password? Yes
Which interfaces do you use (hmip/bidcos/wired)? hmip

**Describe the bug**
Hi, 

I found one things that are strange for HVACs so that they don't deliver the same ways to use them. 

The devices have some additional entities that you can enable: 
![image](https://user-images.githubusercontent.com/66269310/196028298-73eb6cb4-796d-4f44-b82d-ffb84c388f6f.png)

The groups have that information in the CCU as well, but the entities are missing. Could you add those  so that you have the same possibilities (e.g. temperature sensor from the group, set valve level for the group)?

**To Reproduce**
see screenshots of the devices. These things are missing for heating groups

**Screenshots (if applicable)**
see above

**Relevant HA log entries (full log)**
```
not relevant
```

**Diagnostic Information (available on every device)**
```
not relevant, but can be provided if needed
```

**Expected behavior**
The optional entites for the heating group should be as close as posible to the device (at least temp entity and level entity)

**Additional context**
I am using your integration and I am very happy about it for far! Great work.
This is the only thing so far that I discovered...

Thx for your oppinion!

Sebastian
---

**Comment by SukramJ** [comment] 2022-10-16 09:55
Glad you added the requested information from the template, otherwise I would have closed it.

You totally missed which devices you are using.

**Comment by SukramJ** [comment] 2022-10-16 10:04
> The devices have actions for the device in automatisation tasks:
...
The groups are missing there. Could you add those actions for the group device so that you can use them in the same way as an single device?

I cannot reproduce this. Groups are selectable and have actions (hvac_mode, preset).

**Comment by Bascht74** [comment] 2022-10-16 10:55
> Glad you added the requested information from the template, otherwise I would have closed it.
> 
> You totally missed which devices you are using.

I am using HmIP-eTRV-2 and HmIP-WTH-2 devices (some alone, some in groups).

**Comment by Bascht74** [comment] 2022-10-16 10:57
> > The devices have actions for the device in automatisation tasks:
> > ...
> > The groups are missing there. Could you add those actions for the group device so that you can use them in the same way as an single device?
> 
> I cannot reproduce this. Groups are selectable and have actions (hvac_mode, preset).

You are right, I edited the issue and deleted those lines as I found out myself (naming was wrong because I added the groups later on and didn't do a restart to get the namings right). 
So the only nice thing would be to have level and temperature entites for groups as well.

**Comment by Baxxy13** [comment] 2022-10-16 11:04
Temperature-Sensor should be there, Level not.
(left: virt. group-device | right: real eTRV)
![HA_Group_vs_Device](https://user-images.githubusercontent.com/54898249/196031663-ad78b85e-a0a8-4d95-a693-6ca0251ab236.JPG)

But for me it makes no sense to have the "Level" in the group, especially when you have more than one eTRV in your group.

**Comment by Bascht74** [comment] 2022-10-16 11:10
In my system it looks like this: 
![image](https://user-images.githubusercontent.com/66269310/196031922-4a54f5b1-af23-4d6b-9d10-0b76c22f2653.png)

So no temp entity!

**Comment by Bascht74** [comment] 2022-10-16 11:11
All devices in this group got it: 
![image](https://user-images.githubusercontent.com/66269310/196031975-1a41b21f-4f99-4a6b-894e-7bc2d057b0b8.png)

**Comment by SukramJ** [comment] 2022-10-16 11:29
I could add `actual temperature` and `humidity`. LEVEL makes no sense as @Baxxy13 already mentioned.

**Comment by SukramJ** [comment] 2022-10-16 11:29
@Baxxy13 I thing you have `actual temperature` in your unignore file.

**Comment by Baxxy13** [comment] 2022-10-16 11:32
Right. Touched the unignore file long time ago and forgot it.

**Comment by SukramJ** [comment] 2022-10-16 13:55
`actual temperature` and `humidity` have been added with version 1.19.6

**Comment by Bascht74** [comment] 2022-10-16 16:17
Great! Thanks!

**Closed as completed** 2022-10-17 04:03 UTC
