### ISSUE TITLE
HM-Sec-RHS showing up two lowbat entities 

### ISSUE THREAD

**Issue by kabakakao** [SukramJ/hahomematic#186] opened 2022-01-15 07:31 UTC
Make sure you are running the latest version of hahomematic or it's custom_component (and Home Assistant) before reporting an issue.

**custom_component/hahomematic version (if applicable):**
0.22.0

**Home Assistant version (if applicable):**
2021.12.5

**CCU version:**
- Model (CCU2/3, Raspi3/4, NUC, ProxmoxVE, ...): Container
- OS (Original, RaspberryMatic, debmatic/...): piVCCU
- Version: 

**Problem-relevant configuration:**

Do you use tls? No
Do you use callback? No
Do you use username and password? Yes
Which interfaces do you use?

**Describe the bug**
All HM-Sec-RHS Devices create two lowbat entities

**Screenshots**
![54241E17-2C9A-4338-954F-40463AE6B7B3](https://user-images.githubusercontent.com/18161756/149613674-706a04fe-25df-4df0-b71d-67fbd6edfeb3.jpeg)

**Additional context**

**Comment by SukramJ** [comment] 2022-01-15 08:03
I checked the spec and it looks like the device has multiple lowbat parameters.
This is an auto-generated entity, where the integration creates entities based on their paramsets.
We define devices only for more complex types which we call [custom entities](https://github.com/danielperna84/hahomematic/wiki/Homematic-Devices-supported-by-custom-entity).
I don't think this is nice, but this is the expected behavior from integration side, but you can deactivate the obsolete entity in the UI.

@danielperna84 Any Ideas?

**Comment by danielperna84** [comment] 2022-01-15 09:55
Maybe for auto-generated devices we should add a label, or for custom ones. I think we'll get these questions a lot in the future. So I think it would be beneficial if we could add a paragraph to the documentation like _Non-custom devices (see label in device-view) may have duplicate or disfunctional entities. This is __not__ a bug._ Or at least as an boolean attribute of each entity like `custom: false`. Not sure yet how to conveniently transport this fact to the users. In any case, with a related paragraph in the docs we can quickly identify users that haven't read the documentation. 😉

**Comment by kabakakao** [comment] 2022-01-15 11:24
For me it is okay, to hide the entity. I get the same second low battery entity for my HM-Sec-SCo Devices. So if it comes from CCU, feel free to close the issue

**Comment by SukramJ** [comment] 2022-01-15 13:40
@danielperna84
I analyzed the devices in pydevccu
The parameter `LOW_BAT` (HmIP) is always on channel 0.

BidCos devices:
188 devices have `LOWBAT` on channel 0
A total of 18 devices have **additional** LOWBAT parameters on channel 1-5

What i have seen in pyhomematic is that only channel 0 is used for lowbat.

Should i filter out all LOWBAT on channel 1-5?

**Comment by danielperna84** [comment] 2022-01-15 14:02
@SukramJ 

Yes, I think that's the best way to handle this issue.

**Comment by SukramJ** [comment] 2022-01-15 14:48
Fixed with release 0.22.1

**Closed as completed by SukramJ** 2022-01-15 14:48 UTC
